apiVersion: v1
kind: Namespace
metadata:
  name: "{{ proj_nm_logging }}"
  annotations:
    openshift.io/node-selector: ""
  labels:
    openshift.io/cluster-logging: "true"
    openshift.io/cluster-monitoring: "true"
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: "{{ proj_nm_logging }}-logging"
  namespace: "{{ proj_nm_logging }}"
spec:
  targetNamespaces:
  - "{{ proj_nm_logging }}"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "{{ cluster_logging_operator_nm }}"
  namespace: "{{ proj_nm_logging }}"
spec:
  channel: '4.2'
  installPlanApproval: Automatic
  name: "{{ cluster_logging_operator_nm }}"
  source: redhat-operators
  sourceNamespace: openshift-marketplace
