---
  - name: Provision RHAMT
    block:
      - name: Log into OpenShift
        k8s_auth:
          username: "{{ ocp_admin }}"
          password: "{{ ocp_admin_pwd }}"
        register: k8s_auth_results

      - name: "Create {{ proj_nm_infra }} project if it doesn't already exist"
        include: ../../common/createProject.yml
        vars:
          proj_nm: "{{ proj_nm_infra }}"

      - name: Check if RHAMT already deployed
        k8s_info:
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
          validate_certs: no
          namespace: "{{ proj_nm_infra }}"
          kind: Pod
          label_selectors:
            - application = rhamt-web-console
        register: rhamt_pod

      - name: Deploy RHAMT
        include: ../../common/runOcShell.yml
        vars:
          task_name: Deploy RHAMT
          oc_command: "oc process -f ./roles/RHAMT/objects/rhamt.yml -n {{ proj_nm_infra }} | oc create -n {{ proj_nm_infra }} -f -"
        when: rhamt_pod.resources|length == 0

    always:
      - name: If OpenShift login succeeded try to log out
        when: k8s_auth_results.k8s_auth.api_key is defined
        k8s_auth:
          state: absent
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
