apiVersion: v1
kind: ResourceQuota
metadata:
  name: "{{ proj_nm_sandbox }}-quota"
  namespace: "{{ proj_nm_sandbox }}"
spec:
  hard:
    limits.cpu: '2'
    limits.memory: 4Gi
    pods: '4'
    requests.cpu: '1'
    requests.memory: 2Gi
  scopes:
    - NotTerminating
