---
  - name: Download Nexus Operator CRDs
    get_url:
      url: "{{ nexus_operator_crds.baseurl }}{{ item.template_path }}/{{ item.template_nm }}"
      dest: "/tmp/{{ item.template_nm }}"
    loop: "{{ nexus_operator_crds.templates }}"

  - name: Deploy Nexus Operator CRDs
    k8s:
      src: "/tmp/{{ item.template_nm }}"
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    loop: "{{ nexus_operator_crds.templates }}"

    # - name: Get all projects
    #   k8s_info:
    #     api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
    #     kind: Pod
    #     namespace: gpte-operators
    #   register: project_list
    #
    # - name: Print out projects list
    #   debug:
    #     var: project_list
