---
  - name: Provision Logging Infrastructure
    block:
      - name: Log into OpenShift
        k8s_auth:
          username: "{{ ocp_admin }}"
          password: "{{ ocp_admin_pwd }}"
        register: k8s_auth_results

      - name: Install ElasticSearch Operator
        k8s:
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
          validate_certs: no
          namespace: "{{ proj_nm_elasticsearch }}"
          definition: "{{ lookup('template', '../objects/elasticsearch-operator.yml') }}"

      - name: Wait for ElasticSearch Operator to spin up
        k8s_info:
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
          validate_certs: no
          namespace: "{{ proj_nm_elasticsearch }}"
          api_version: apps/v1
          kind: Deployment
          name: "{{ elasticsearch_operator_nm }}"
        register: elasticsearch_operator_deployment
        until: elasticsearch_operator_deployment.resources is defined and elasticsearch_operator_deployment.resources|length == 1 and elasticsearch_operator_deployment.resources[0].status.readyReplicas is defined and elasticsearch_operator_deployment.resources[0].status.readyReplicas == 1 and elasticsearch_operator_deployment.resources[0].status.availableReplicas is defined and elasticsearch_operator_deployment.resources[0].status.availableReplicas == 1
        retries: 50
        delay: 10

      - name: Install cluster logging Operator
        k8s:
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
          validate_certs: no
          namespace: "{{ proj_nm_logging }}"
          definition: "{{ lookup('template', '../objects/cluster-logging-operator.yml') }}"

      - name: Wait for cluster logging Operator to spin up
        k8s_info:
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
          validate_certs: no
          namespace: "{{ proj_nm_logging }}"
          api_version: apps/v1
          kind: Deployment
          name: "{{ cluster_logging_operator_nm }}-operator"
        register: cluster_logging_operator_deployment
        until: cluster_logging_operator_deployment.resources is defined and cluster_logging_operator_deployment.resources|length == 1 and cluster_logging_operator_deployment.resources[0].status.readyReplicas is defined and cluster_logging_operator_deployment.resources[0].status.readyReplicas == 1 and cluster_logging_operator_deployment.resources[0].status.availableReplicas is defined and cluster_logging_operator_deployment.resources[0].status.availableReplicas == 1
        retries: 50
        delay: 10

      - name: Install cluster logging
        k8s:
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
          validate_certs: no
          namespace: "{{ proj_nm_logging }}"
          definition: "{{ lookup('template', '../objects/cluster-logging.yml') }}"

    always:
      - name: If OpenShift login succeeded try to log out
        when: k8s_auth_results.k8s_auth.api_key is defined
        k8s_auth:
          state: absent
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
