apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: codeready-workspaces-operator-group
  namespace: "{{ proj_nm_infra }}"
spec:
  targetNamespaces:
    - "{{ proj_nm_infra }}"
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: codeready-workspaces
  namespace: "{{ proj_nm_infra }}"
  labels:
    app.kubernetes.io/part-of: codeready-workspaces
    app: codeready-workspaces
spec:
  channel: latest
  name: codeready-workspaces
  source: redhat-operators
  sourceNamespace: openshift-marketplace
