apiVersion: org.eclipse.che/v1
kind: CheCluster
metadata:
  name: codeready-workspaces
  namespace: "{{ proj_nm_infra }}"
  labels:
    app.kubernetes.io/part-of: codeready-workspaces
    app: codeready-workspaces
spec:
  server:
    cheFlavor: codeready
    tlsSupport: false
    selfSignedCert: false
    customCheProperties:
      # CHE_WORKSPACE_DEFAULT__MEMORY__LIMIT__MB: "2048"
      # CHE_INFRA_KUBERNETES_NAMESPACE_DEFAULT: "{{ crw_workspaces_namespace }}"
      CHE_WORKSPACE_JAVA__OPTIONS: "-XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms512m -Djava.security.egd=file:/dev/./urandom"
      CHE_WORKSPACE_MAVEN__OPTIONS: "-XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xms512m -Djava.security.egd=file:/dev/./urandom"
  database:
    externalDB: false
  auth:
    openShiftoAuth: true
  storage:
    pvcStrategy: per-workspace
    pvcClaimSize: 1Gi
    preCreateSubPaths: true
