---
 - name: Provision OpenShift Pipelines
   block: 
     - name: Log into OpenShift
       k8s_auth:
         username: "{{ ocp_admin }}"
         password: "{{ ocp_admin_pwd }}"
       register: k8s_auth_results

     - name: Install OpenShift Pipelines Operator 
       k8s:
         api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
         validate_certs: no
         definition: "{{ lookup('template', '../objects/openshift-pipelines-operator.yml') }}"

     - name: Wait for OpenShift Pipelines Operator to spin up
       k8s_info:
         api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
         validate_certs: no
         namespace: openshift-operators
         api_version: apps/v1
         kind: Deployment
         name: openshift-pipelines-operator
       register: pipelines_operator_deployment
       until: pipelines_operator_deployment.resources is defined and pipelines_operator_deployment.resources|length == 1 and pipelines_operator_deployment.resources[0].status.readyReplicas is defined and pipelines_operator_deployment.resources[0].status.readyReplicas == 1 and pipelines_operator_deployment.resources[0].status.availableReplicas is defined and pipelines_operator_deployment.resources[0].status.availableReplicas == 1
       retries: 50
       delay: 10

   always:
      - name: If OpenShift login succeeded try to log out
        when: k8s_auth_results.k8s_auth.api_key is defined
        k8s_auth:
          state: absent
          api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
